pipeline {
    agent any

    tools {
        maven 'maven-3.6.3' 
        jdk 'jdk17' 
    }

    stages {
        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/New_demo/my-app") { 
                    sh 'mvn -B -DskipTests clean package' 
                }
            }
        }
    }
}
